name: PR Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Install SGD
        run: echo y | sf plugins install sfdx-git-delta

      - name: Authenticate QA Sandbox
        run: |
          echo "${{ secrets.SFDX_AUTH_URL_QA }}" > auth.txt
          sf org login sfdx-url --sfdx-url-file auth.txt --alias qa

      - name: Generate Delta
        run: |
          mkdir delta
          sf sgd source delta \
            --to HEAD \
            --from origin/develop \
            --output-dir delta

      - name: Determine Tests to Run
        run: |
          TESTS=""

          if grep -q "LeaveTriggerHelper" delta/package/package.xml; then
            TESTS="${TESTS}LeaveTriggerTest,"
          fi

          TESTS=$(echo $TESTS | sed 's/,$//')

          echo "TESTS=$TESTS" >> $GITHUB_ENV
          echo "Tests to run: $TESTS"

      - name: Validate Deployment
        run: |
          if [ -n "$TESTS" ]; then
            sf project deploy validate \
              --manifest delta/package/package.xml \
              --target-org qa \
              --test-level RunSpecifiedTests \
              --tests "$TESTS"
          else
            echo "No Apex tests required."
          fi